# Generated by Django 5.2 on 2025-09-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='message',
            field=models.TextField(blank=True, default='I want to join the club.'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
